arm:
#  mac: "MAC"
  mac: "Static MAC"
  hostname: "Hostname"
  owner: "Власник"
  pc_type: "Тип ПК"
  ip: "IP"
  randmac: "Random MAC"
mkp:
  mac: "Статичний MAC"
  model: "Модель"
  owner: "Відповідальний"
  mkp_type: "Тип МКП"
  randmac: "Динамічний MAC"
dhcp:
  mac: "mac"
  name: "name"
  ip: "ip"
  firstDate: "firstDate"
  lastDate: "lastDate"
  source: "source"
validation:
  ip: "ip"
  mac: "mac"
report:
  ipmac: "ipmac"
verified:
  mac: "mac"
report1:
  source: "source"
  verified: "verified"
  type: "type"
  name: "name"
  ipmac: "ipmac"
  note: "note"
pending:
  type: "type"
  source: "source"
  ip: "ip"
  mac: "mac"
  name: "name"
  firstDate: "firstDate"
  lastDate: "lastDate"
