arm:
  # mac: "MAC"
  # mac: "staticMac"
  mac: "staticMac"
  hostname: "hostname"
  # owner: "owner"
  owner: "owner"
  pc_type: "pcType"
  # pc_type: "Тип ПК"
  ip: "ip"
  # randmac: "randomMac"
  randmac: "randomMac"
  ownership: "pcOwning"
mkp:
  mac: "staticMac"
  model: "model"
  owner: "responsible"
  mkp_type: "phoneType"
  randmac: "randomMac"
  category: "phoneCategory"
dhcp:
  mac: "mac"
  name: "name"
  ip: "ip"
  firstDate: "firstDate"
  lastDate: "lastDate"
  source: "source"
validation:
  ip: "ip"
  mac: "mac"
report:
  ipmac: "ipmac"
verified:
  mac: "mac"
report1:
  source: "source"
  verified: "verified"
  type: "type"
  name: "name"
  ipmac: "ipmac"
  note: "note"
pending:
  type: "type"
  source: "source"
  ip: "ip"
  mac: "mac"
  name: "name"
  firstDate: "firstDate"
  lastDate: "lastDate"
