arm:
  mac:
    - "staticMac"
    - "Static MAC"
  hostname:
    - "hostname"
    - "Hostname"
  owner:
    - "owner"
    - "Власник"
  pc_type:
    - "pcType"
    - "Тип ПК"
  ip:
    - "ip"
    - "IP"
  randmac:
    - "randomMac"
    - "Random MAC"
  ownership:
    - "pcOwning"
    - "Власність"
mkp:
  mac:
    - "staticMac"
    - "Статичний MAC"
  model:
    - "model"
    - "Модель"
  owner:
    - "responsible"
    - "Відповідальний"
  mkp_type:
    - "phoneType"
    - "Тип МКП"
  randmac:
    - "randomMac"
    - "Динамічний MAC"
  category:
    - "phoneCategory"
    - "Категорія МКП"
dhcp:
  mac: "mac"
  name: "name"
  ip: "ip"
  firstDate: "firstDate"
  lastDate: "lastDate"
  source: "source"
  count: "count"
  randomized: "randomized"
validation:
  ip: "ip"
  mac: "mac"
report:
  ipmac: "ipmac"
verified:
  mac: "mac"
report1:
  source: "source"
  verified: "verified"
  type: "type"
  name: "name"
  ipmac: "ipmac"
  note: "note"
pending:
  type: "type"
  source: "source"
  ip: "ip"
  mac: "mac"
  name: "name"
  firstDate: "firstDate"
  lastDate: "lastDate"
